name: Build & Deploy (Angular + API to single Windows App Service)

on:
  push:
    branches: [ main ]
    paths:
      - 'client/**'
      - 'server/**'
      - '.github/workflows/main_antoinerahme.yml'

jobs:
  build-deploy:
    runs-on: windows-latest   # windows runner to match paths

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # -------- Build Angular --------
      - name: Build Angular
        working-directory: client
        run: |
          npm ci
          npx ng build --configuration production

          # Find the folder that contains index.html under dist
          BUILD_ROOT=$(find dist -type f -name index.html -printf '%h\n' | head -n 1)
          if [ -z "$BUILD_ROOT" ]; then echo "index.html not found under client/dist"; exit 1; fi
          echo "Angular build root: $BUILD_ROOT"

          # Copy SPA web.config into the build root
          cp client/web.config "$BUILD_ROOT/web.config"

          # Export for later steps
          echo "BUILD_ROOT=$BUILD_ROOT" >> $GITHUB_ENV


      # -------- Publish API --------
      - name: Publish API
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'
      - name: dotnet publish
        shell: pwsh
        working-directory: server/Hn.Api
        run: dotnet publish -c Release -o $env:GITHUB_WORKSPACE\api-publish

      # -------- Stage unified package (root = SPA, /api = API) --------
      - name: Prepare package
        run: |
          mkdir -p package/wwwroot
          cp -r "$BUILD_ROOT/"* package/wwwroot/
          mkdir -p package/wwwroot/api
          cp -r api-publish/* package/wwwroot/api/

      # -------- Deploy to Windows App Service --------
      - name: Deploy
        uses: azure/webapps-deploy@v3
        with:
          app-name: antoinerahme
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: ${{ github.workspace }}\package\wwwroot
